FROM jboss/wildfly

LABEL maintainer="ioexcept@gmail.com"
LABEL version="1.1"
LABEL name="wildfly-example"
LABEL type="webapp"
LABEL project="https://github.com/ssgeejr/wildfly-example"

ADD wwa.war /opt/jboss/wildfly/standalone/deployments/
